services:
  web:
    image: nginx:1.21.1-alpine
    container_name: tpl_nginx
    env_file: .env
    ports:
      - 8082:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/app.conf.template:/etc/nginx/templates/app.conf.template
    depends_on:
      - php
  php:
    build: 
      context: ./php-fpm
      target: localdev
    container_name: tpl_php
    user: ${WEB_UID}:${WEB_GID}
    volumes:
      - ./app:/var/www/app
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/supervisord.conf:/etc/supervisord.conf
      - ./php-fpm/run.sh:/run.sh
    depends_on:
      - db
  db:
    image: mariadb
    container_name: tpl_mariadb
    env_file: .env
    ports:
    - 3306:3306
    volumes:
      - tpl_mysqldata:/var/lib/mysql
    restart: always
  adminer:
    image: adminer
    container_name: tpl_adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: tpl_rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:alpine
    container_name: tpl_redis
    restart: always
    ports:
      - 63791:6379
    command: redis-server
    volumes: 
      - tpl_redisdata:/data
volumes:
  tpl_mysqldata:
  tpl_redisdata:
